version: '3'

services: 
    nginx:
        build: 
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports: 
            - "8080:8080"
        depends_on:
            - "go1"
            - "go2"
    
    go1:
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile

    go2:
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile