// Code generated by protoc-gen-go. DO NOT EDIT.
// source: laptop_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLaptopRequest struct {
	Laptop               *Laptop  `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLaptopRequest) Reset()         { *m = CreateLaptopRequest{} }
func (m *CreateLaptopRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLaptopRequest) ProtoMessage()    {}
func (*CreateLaptopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{0}
}

func (m *CreateLaptopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLaptopRequest.Unmarshal(m, b)
}
func (m *CreateLaptopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLaptopRequest.Marshal(b, m, deterministic)
}
func (m *CreateLaptopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaptopRequest.Merge(m, src)
}
func (m *CreateLaptopRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLaptopRequest.Size(m)
}
func (m *CreateLaptopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaptopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaptopRequest proto.InternalMessageInfo

func (m *CreateLaptopRequest) GetLaptop() *Laptop {
	if m != nil {
		return m.Laptop
	}
	return nil
}

type CreateLapTopResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLapTopResponse) Reset()         { *m = CreateLapTopResponse{} }
func (m *CreateLapTopResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLapTopResponse) ProtoMessage()    {}
func (*CreateLapTopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{1}
}

func (m *CreateLapTopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLapTopResponse.Unmarshal(m, b)
}
func (m *CreateLapTopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLapTopResponse.Marshal(b, m, deterministic)
}
func (m *CreateLapTopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLapTopResponse.Merge(m, src)
}
func (m *CreateLapTopResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLapTopResponse.Size(m)
}
func (m *CreateLapTopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLapTopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLapTopResponse proto.InternalMessageInfo

func (m *CreateLapTopResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SearchLaptopRequest struct {
	Filter               *Filter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchLaptopRequest) Reset()         { *m = SearchLaptopRequest{} }
func (m *SearchLaptopRequest) String() string { return proto.CompactTextString(m) }
func (*SearchLaptopRequest) ProtoMessage()    {}
func (*SearchLaptopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{2}
}

func (m *SearchLaptopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchLaptopRequest.Unmarshal(m, b)
}
func (m *SearchLaptopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchLaptopRequest.Marshal(b, m, deterministic)
}
func (m *SearchLaptopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchLaptopRequest.Merge(m, src)
}
func (m *SearchLaptopRequest) XXX_Size() int {
	return xxx_messageInfo_SearchLaptopRequest.Size(m)
}
func (m *SearchLaptopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchLaptopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchLaptopRequest proto.InternalMessageInfo

func (m *SearchLaptopRequest) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type SearchLaptopResponse struct {
	Laptop               *Laptop  `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchLaptopResponse) Reset()         { *m = SearchLaptopResponse{} }
func (m *SearchLaptopResponse) String() string { return proto.CompactTextString(m) }
func (*SearchLaptopResponse) ProtoMessage()    {}
func (*SearchLaptopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{3}
}

func (m *SearchLaptopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchLaptopResponse.Unmarshal(m, b)
}
func (m *SearchLaptopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchLaptopResponse.Marshal(b, m, deterministic)
}
func (m *SearchLaptopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchLaptopResponse.Merge(m, src)
}
func (m *SearchLaptopResponse) XXX_Size() int {
	return xxx_messageInfo_SearchLaptopResponse.Size(m)
}
func (m *SearchLaptopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchLaptopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchLaptopResponse proto.InternalMessageInfo

func (m *SearchLaptopResponse) GetLaptop() *Laptop {
	if m != nil {
		return m.Laptop
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateLaptopRequest)(nil), "techschool.pcbook.go.CreateLaptopRequest")
	proto.RegisterType((*CreateLapTopResponse)(nil), "techschool.pcbook.go.CreateLapTopResponse")
	proto.RegisterType((*SearchLaptopRequest)(nil), "techschool.pcbook.go.SearchLaptopRequest")
	proto.RegisterType((*SearchLaptopResponse)(nil), "techschool.pcbook.go.SearchLaptopResponse")
}

func init() {
	proto.RegisterFile("laptop_service.proto", fileDescriptor_240c60d9fb227e71)
}

var fileDescriptor_240c60d9fb227e71 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0xd7, 0x1e, 0x06, 0x7e, 0x4e, 0x0f, 0xb1, 0x07, 0x29, 0x1e, 0xa4, 0x88, 0xa8, 0x48,
	0x90, 0xe9, 0x2f, 0x50, 0xf0, 0xe2, 0x0e, 0xd2, 0x79, 0xf2, 0x22, 0x49, 0xf6, 0xd9, 0x46, 0x3b,
	0xbf, 0x98, 0x64, 0xfb, 0xc3, 0xfe, 0x11, 0x59, 0x1b, 0xa5, 0xc3, 0x4c, 0xc1, 0x6b, 0x79, 0xdf,
	0xf7, 0xc9, 0xf7, 0x50, 0xc8, 0x1a, 0x61, 0x3c, 0x99, 0x27, 0x87, 0x76, 0xa9, 0x15, 0x72, 0x63,
	0xc9, 0x13, 0xcb, 0x3c, 0xaa, 0xda, 0xa9, 0x9a, 0xa8, 0xe1, 0x46, 0x49, 0xa2, 0x57, 0x5e, 0x51,
	0xfe, 0x95, 0x9d, 0xa3, 0x73, 0xa2, 0x0a, 0xd9, 0x3c, 0x7b, 0xd6, 0x8d, 0x47, 0xbb, 0xfe, 0xb5,
	0xb8, 0x83, 0xbd, 0x1b, 0x8b, 0xc2, 0xe3, 0xa4, 0xed, 0x94, 0xf8, 0xbe, 0x40, 0xe7, 0xd9, 0x15,
	0x0c, 0xbb, 0x91, 0xfd, 0xe4, 0x30, 0x39, 0xd9, 0x1e, 0x1f, 0xf0, 0x18, 0x89, 0x87, 0x52, 0xc8,
	0x16, 0xc7, 0x90, 0x7d, 0x8f, 0x3d, 0xac, 0xc6, 0x9c, 0xa1, 0x37, 0x87, 0x6c, 0x17, 0x52, 0x3d,
	0x6b, 0x97, 0xb6, 0xca, 0x54, 0xcf, 0x56, 0xd0, 0x29, 0x0a, 0xab, 0xea, 0x1f, 0xd0, 0xee, 0x8d,
	0xbf, 0x43, 0x6f, 0xdb, 0x4c, 0x19, 0xb2, 0xc5, 0x04, 0xb2, 0xf5, 0xb1, 0x00, 0xfd, 0xd7, 0x09,
	0xe3, 0x8f, 0x04, 0x76, 0xba, 0xd7, 0x4f, 0x3b, 0xd3, 0xac, 0x82, 0x51, 0xdf, 0x10, 0x3b, 0x8d,
	0xef, 0x44, 0x2c, 0xe6, 0x67, 0x7f, 0x44, 0x7b, 0x8e, 0x8a, 0x01, 0xd3, 0x30, 0xea, 0x1f, 0xb2,
	0x09, 0x14, 0x31, 0xb7, 0x09, 0x14, 0xf3, 0x52, 0x0c, 0x2e, 0x92, 0xeb, 0x73, 0x38, 0xaa, 0xb4,
	0xaf, 0x17, 0x92, 0x2b, 0x9a, 0x87, 0xae, 0xed, 0x75, 0x5f, 0xc4, 0x52, 0x70, 0x23, 0xef, 0x93,
	0xc7, 0xd4, 0x48, 0x39, 0x6c, 0x7f, 0x95, 0xcb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x1e,
	0x53, 0x80, 0x84, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LapTopServiceClient is the client API for LapTopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LapTopServiceClient interface {
	CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLapTopResponse, error)
	SearchLaptop(ctx context.Context, in *SearchLaptopRequest, opts ...grpc.CallOption) (LapTopService_SearchLaptopClient, error)
}

type lapTopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLapTopServiceClient(cc grpc.ClientConnInterface) LapTopServiceClient {
	return &lapTopServiceClient{cc}
}

func (c *lapTopServiceClient) CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLapTopResponse, error) {
	out := new(CreateLapTopResponse)
	err := c.cc.Invoke(ctx, "/techschool.pcbook.go.LapTopService/CreateLaptop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lapTopServiceClient) SearchLaptop(ctx context.Context, in *SearchLaptopRequest, opts ...grpc.CallOption) (LapTopService_SearchLaptopClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LapTopService_serviceDesc.Streams[0], "/techschool.pcbook.go.LapTopService/SearchLaptop", opts...)
	if err != nil {
		return nil, err
	}
	x := &lapTopServiceSearchLaptopClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LapTopService_SearchLaptopClient interface {
	Recv() (*SearchLaptopResponse, error)
	grpc.ClientStream
}

type lapTopServiceSearchLaptopClient struct {
	grpc.ClientStream
}

func (x *lapTopServiceSearchLaptopClient) Recv() (*SearchLaptopResponse, error) {
	m := new(SearchLaptopResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LapTopServiceServer is the server API for LapTopService service.
type LapTopServiceServer interface {
	CreateLaptop(context.Context, *CreateLaptopRequest) (*CreateLapTopResponse, error)
	SearchLaptop(*SearchLaptopRequest, LapTopService_SearchLaptopServer) error
}

// UnimplementedLapTopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLapTopServiceServer struct {
}

func (*UnimplementedLapTopServiceServer) CreateLaptop(ctx context.Context, req *CreateLaptopRequest) (*CreateLapTopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLaptop not implemented")
}
func (*UnimplementedLapTopServiceServer) SearchLaptop(req *SearchLaptopRequest, srv LapTopService_SearchLaptopServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchLaptop not implemented")
}

func RegisterLapTopServiceServer(s *grpc.Server, srv LapTopServiceServer) {
	s.RegisterService(&_LapTopService_serviceDesc, srv)
}

func _LapTopService_CreateLaptop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaptopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LapTopServiceServer).CreateLaptop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/techschool.pcbook.go.LapTopService/CreateLaptop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LapTopServiceServer).CreateLaptop(ctx, req.(*CreateLaptopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LapTopService_SearchLaptop_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchLaptopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LapTopServiceServer).SearchLaptop(m, &lapTopServiceSearchLaptopServer{stream})
}

type LapTopService_SearchLaptopServer interface {
	Send(*SearchLaptopResponse) error
	grpc.ServerStream
}

type lapTopServiceSearchLaptopServer struct {
	grpc.ServerStream
}

func (x *lapTopServiceSearchLaptopServer) Send(m *SearchLaptopResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LapTopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "techschool.pcbook.go.LapTopService",
	HandlerType: (*LapTopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLaptop",
			Handler:    _LapTopService_CreateLaptop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchLaptop",
			Handler:       _LapTopService_SearchLaptop_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "laptop_service.proto",
}
